package common;


	import java.util.HashSet;
	import java.util.Set;
	import javax.persistence.Column;
	import javax.persistence.Entity;
	import javax.persistence.FetchType;
	import javax.persistence.GeneratedValue;
	import static javax.persistence.GenerationType.IDENTITY;
	import javax.persistence.Id;
	import javax.persistence.NamedNativeQueries;
	import javax.persistence.NamedNativeQuery;
	import javax.persistence.OneToMany;
	import javax.persistence.OneToOne;
	import javax.persistence.Table;
	import javax.persistence.Transient;
	import javax.persistence.UniqueConstraint;

	import org.hibernate.annotations.Cascade;
	import org.hibernate.annotations.CascadeType;
	import org.hibernate.annotations.Filter;
	import org.hibernate.annotations.FilterDef;
	import org.hibernate.annotations.ParamDef;
	import org.hibernate.annotations.NamedQueries;
	import org.hibernate.annotations.NamedQuery;

	import interceptor.IAuditLog;

	/**
	 * Stock generated by hbm2java
	 */
	@NamedQueries({
		@NamedQuery(
		name = "findStockByStockCode",
		query = "from Stock s where s.stockCode = :stockCode"
		)
	})
	@NamedNativeQueries({
		@NamedNativeQuery(
		name = "findStockByStockCodeNativeSQL",
		query = "select s.stock_code from stock s where s.stock_code = :stockCode",
		resultClass = Stock.class
		),
		@NamedNativeQuery(
		name = "callStockStoreProcedure",
		query = "CALL GetStocks(:stockCode)",
		resultClass = Stock.class
		)
	})
	@Entity
	@FilterDef(name="stockRecordFilter", parameters=@ParamDef( name="stockRecordFilterParam", type="date" ) )
	@Table(name = "stock", catalog = "hibernatedb", uniqueConstraints = {
			@UniqueConstraint(columnNames = "STOCK_NAME"),
			@UniqueConstraint(columnNames = "STOCK_CODE") })
	public class Stock implements java.io.Serializable, IAuditLog {

		private Integer stockId;
		private String stockCode;
		private String stockName;
		

		public Stock() {
		}

		public Stock(String stockCode, String stockName) {
			this.stockCode = stockCode;
			this.stockName = stockName;
		}

	

		@Id
		@GeneratedValue(strategy = IDENTITY)
		@Column(name = "STOCK_ID", unique = true, nullable = false)
		public Integer getStockId() {
			return this.stockId;
		}

		public void setStockId(Integer stockId) {
			this.stockId = stockId;
		}

		@Column(name = "STOCK_CODE", unique = true, nullable = false, length = 10)
		public String getStockCode() {
			return this.stockCode;
		}

		public void setStockCode(String stockCode) {
			this.stockCode = stockCode;
		}

		@Column(name = "STOCK_NAME", unique = true, nullable = false, length = 20)
		public String getStockName() {
			return this.stockName;
		}

		public void setStockName(String stockName) {
			this.stockName = stockName;
		}

		
		
		@Transient
		@Override
		public Long getId(){
			return this.stockId.longValue();
		}
		
		@Transient
		@Override
		public String getLogDeatil(){
			StringBuilder sb = new StringBuilder();
			sb.append(" Stock Id : ").append(stockId)
			.append(" Stock Code : ").append(stockCode)
			.append(" Stock Name : ").append(stockName);

			return sb.toString();
		}
		
	}


